import 'package:flutter/material.dart';
import 'shell/app_shell.dart';
import 'screens/onboarding_screen.dart';
import 'screens/login_screen.dart';
import 'core/themes.dart';
import 'core/theme_controller.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/foundation.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final isMobile = defaultTargetPlatform == TargetPlatform.android ||
      defaultTargetPlatform == TargetPlatform.iOS;
  if (isMobile) {
    // Mobile uses platform config files (google-services.json/GoogleService-Info.plist)
    await Firebase.initializeApp();
  } else {
    // Desktop uses explicit options generated by FlutterFire CLI.
    try {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    } catch (_) {
      // Keep running; login will fail until options are replaced with real values.
    }
  }
  await ThemeController.instance.load();
  runApp(const GreenGainsApp());
}

class GreenGainsApp extends StatefulWidget {
  const GreenGainsApp({super.key});

  @override
  State<GreenGainsApp> createState() => _GreenGainsAppState();
}

class _GreenGainsAppState extends State<GreenGainsApp> {
  bool? _lastDark;

  void _applySystemUi(bool isDark) {
    if (_lastDark == isDark) return;
    _lastDark = isDark;
    // Schedule to avoid doing this during build/layout.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: isDark ? Brightness.light : Brightness.dark,
        statusBarBrightness: isDark ? Brightness.dark : Brightness.light,
      ));
    });
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: ThemeController.instance,
      builder: (context, _) {
        final mode = ThemeController.instance.mode;
        final isDark = mode == ThemeMode.dark;
        _applySystemUi(isDark);
        return MaterialApp(
          title: 'GreenGains',
          theme: AppTheme.theme(),
          darkTheme: AppTheme.themeDark(),
          themeMode: mode,
          themeAnimationDuration: const Duration(milliseconds: 120),
          themeAnimationCurve: Curves.easeInOut,
          home: const RootDecider(),
        );
      },
    );
  }
}

class RootDecider extends StatefulWidget {
  const RootDecider({super.key});

  @override
  State<RootDecider> createState() => _RootDeciderState();
}

class _RootDeciderState extends State<RootDecider> {
  bool? _showOnboarding;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    final seen = prefs.getBool('onboarding_complete') ?? false;
    if (!mounted) return;
    setState(() => _showOnboarding = !seen);
  }

  Future<void> _completeOnboarding() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('onboarding_complete', true);
    if (!mounted) return;
    setState(() => _showOnboarding = false);
  }

  @override
  Widget build(BuildContext context) {
    if (_showOnboarding == null) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }
    if (_showOnboarding == true) {
      return OnboardingScreen(onDone: _completeOnboarding);
    }
    return const AuthGate();
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        final user = snapshot.data;
        if (user != null) {
          return const AppShell();
        }
        return const LoginScreen();
      },
    );
  }
}
